baseURL = "https://rn.github.io/"
languageCode = "en-us"
title = "Rolf Neugebauer's Blog"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  facebook = ""
  twitter = "https://twitter.com/neugebar"
  instagram = ""
  youtube = ""
  github = "https://github.com/rn"
  linkedin = "https://www.linkedin.com/in/rneugeba"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/reichstag.jpg"
  recent_posts_number = 5
